version: "3.3"
services:
  web:
    restart: always
    build: .
    image: waf-deser
    
  waf:
    image:  nginx:1.16
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - web