version: '3'

services:
  php-app:
    build:
      context: ./src/src
    ports:
      - "45679:80"
    volumes:
      - ./dist/src:/var/www/html
    depends_on:
      - mysql-db
    restart: always

  mysql-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: ctf
      MYSQL_PASSWORD: VeryRandomPassword
      MYSQL_DATABASE: bypassssss
      MYSQL_ROOT_PASSWORD: SuperRandomPassword
    volumes:
      - ./dist/database/db.sql:/docker-entrypoint-initdb.d/db.sql
