version: "3"
services:
    web:
        build: ./web
        ports:
            - "80:80"
            - "5432"
            - "8000"
        environment:
            POSTGRES_HOST: "127.0.0.1"
            POSTGRES_DB: notes_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 98896938d4daff23ba44019dc52a55bb
            SECRET_KEY: 43b2ffa01a257cab142ec98fe296851a
            BASE_URL: http://127.0.0.1
            BOT_URL: http://127.0.0.1:8000
    db:
        image: postgres:latest
        environment:
            POSTGRES_HOST: "127.0.0.1"
            POSTGRES_DB: notes_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 98896938d4daff23ba44019dc52a55bb
        network_mode: service:web
    bot:
        build: ./bot
        environment:
            FLAG: INTIGRITI{plz_solve_locally_first_THEN_repeat_on_remote_server}
            BASE_URL: http://127.0.0.1
        network_mode: service:web
