services:
  proxy:
    build: ./proxy
    ports:
      - "80:80"
    networks:
      - backend
  app:
    build: ./app
    ports:
      - "8000:8000"
    networks:
      - backend
  admin:
    build: ./admin
    ports:
      - "5002:5002"
    networks:
      - backend

networks:
  backend:
    driver: bridge
